swagger: "2.0"
info:
  version: "0.0.1"
  title: Sample API
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /healthcheck:
    # our controller name
    x-swagger-router-controller: status
    get:
      operationId: getStatus
      description: get service status
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetStatusResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GetStatusResponse:
    required:
      - myapplication
    properties:
      myapplication:
        type: array
        items:
          type: object
          properties:
            version:
              type: string
            description:
              type: string